#!/usr/bin/env bash

# Please put the full path to this directory
# e.g. you can find this by using the pwd command in the terminal
home_directory="/panfs/panasas01/sscm/gh13047/sandpit/godmc/relateds"

# Input data files
betas="${home_directory}/input_data/methylation_betas/FILENAME"
bfile_raw="${home_directory}/input_data/plink_files/FILENAME"
covariates="${home_directory}/input_data/covariates/FILENAME"

# Options
unrelated="yes"

# Number of threads to use per node
nthreads="16"


source ${home_directory}/parameters
