#!/usr/bin/env bash



# Computer

# Input data files
methylation_data=""
geno_data=""
covariates_data=""


# Created files

grmfile_all=


# Options
unrelated="TRUE"




idat file name
bplink file name
covariates filename
phenotypes filename
family or unrelated
