#!/usr/bin/env bash

# Clean genetic data
bfile="${home_directory}/input_data/genetic_data/data"

# Kinship files
grmfile_all="${home_directory}/input_data/genetic_data/data"
grmfile_relateds="${home_directory}/input_data/genetic_data/data_relateds"
grmfile_unrelateds="${home_directory}/input_data/genetic_data/data_unrelateds"

# PCA files
pcs_all="${grmfile_all}.eigenvec"

# SNP list files
hm3_snps="${home_directory}/resources/hapmap3_autosome.snplist.gz"
ilmn_probesnps="${home_directory}/resources/qc/probesnps.txt"

# Sample mixup checks
bfile_probesnps="${bfile}_probesnps"

# GRM parameters
rel_cutoff=0.125
grm_maf_cutoff=0.01

# PCA paramaters
n_pcs=10
pca_sd=3

# Matrixeqtl parameters
bfile_chunksize=10000
soft_threshold="1e-7"
soft_threshold_cnv="1e-3"

# ID lists
genetic_outlier_ids="${home_directory}/input_data/genetic_data/genetic_outliers.txt"
methylation_ids="${home_directory}/input_data/genetic_data/methylation_ids.txt"

# Methylation files
methylation_rt="${home_directory}/input_data/methylation_data/methylation_rt.txt"
methylation_rt_cc="${home_directory}/input_data/methylation_data/methylation_rt_cc.txt"
methylation_rt_cc_sq="${home_directory}/input_data/methylation_data/methylation_rt_cc_sq.txt"
methylation_rt_poly="${home_directory}/input_data/methylation_data/methylation_rt_poly.txt"


# logfiles




# scripts and binaries

plink="${home_directory}/bin/plink1.90"
gcta="${home_directory}/bin/gcta64"


matrixeqtl_run_r="${home_directory}/resources/genetics/matrixeqtl.R"





# bplink file name
# covariates filename
# phenotypes filename
# family or unrelated

# kinship file
# kinship file - relateds only

# genetic principal components
# smoking prediction
# age prediction

# cell count reference
# cell counts

# cnv file
