#!/usr/bin/env bash

# Clean genetic data
bfile="${home_directory}/processed_data/genetic_data/data"
tabfile="${home_directory}/processed_data/genetic_data/tabfile/data"
allele_ref="${home_directory}/processed_data/genetic_data/data.allele_codes"

# cnv file
tabcnv="${home_directory}/processed_data/cnv_data/tabfile/data"

# Kinship files
grmfile_all="${home_directory}/processed_data/genetic_data/data"
grmfile_relateds="${home_directory}/processed_data/genetic_data/data_relateds"
grmfile_unrelateds="${home_directory}/processed_data/genetic_data/data_unrelateds"

# PCA files
pcs_all="${grmfile_all}.eigenvec"

# Cell count
cellcounts="${home_directory}/processed_data/methylation_data/cellcounts.txt"

# Covariates
covariates_combined="${home_directory}/processed_data/methylation_data/all_covaraites.txt"

# SNP list files
hm3_snps="${home_directory}/resources/genetics/hapmap3_autosome.snplist.gz"
ilmn_probesnps="${home_directory}/resources/qc/probesnps.txt"

# Sample mixup checks
bfile_probesnps="${bfile}_probesnps"

# GRM parameters
rel_cutoff=0.125
grm_maf_cutoff=0.01

# PCA paramaters
n_pcs=10
pca_sd=3

# Matrixeqtl parameters
bfile_chunksize=10000
soft_threshold="1e-7"
soft_threshold_cnv="1e-7"

# ID lists
genetic_outlier_ids="${home_directory}/processed_data/genetic_data/genetic_outliers.txt"
methylation_ids="${home_directory}/processed_data/genetic_data/methylation_ids.txt"

# Methylation files
methylation_rt="${home_directory}/processed_data/methylation_data/methylation_rt.txt"
methylation_rt_cc="${home_directory}/processed_data/methylation_data/methylation_rt_cc.txt"
methylation_rt_cc_sq="${home_directory}/processed_data/methylation_data/methylation_rt_cc_sq.txt"
methylation_rt_poly="${home_directory}/processed_data/methylation_data/methylation_rt_poly.txt"

# Smoking prediction
smoking_pred="${home_directory}/processed_data/methylation_data/smoking_prediction.txt"

# Age prediction
age_pred="${home_directory}/processed_data/methylation_data/age_prediction.txt"

# Results locations
ewas_bmi_dir="${home_directory}/results/ewas_bmi"
ewas_height_dir="${home_directory}/results/ewas_height"
gwas_aar_dir="${home_directory}/results/gwas_aar"
gwas_cellcounts_dir="${home_directory}/results/gwas_cellcounts"
gwas_smoking_dir="${home_directory}/results/gwas_smoking"
matrixeqtl_mcnv_dir="${home_directory}/results/matrixeqtl_mcnv"
matrixeqtl_mqtl_dir="${home_directory}/results/matrixeqtl_mqtl"
matrixeqtl_vmqtl_dir="${home_directory}/results/matrixeqtl_vmqtl"
resname="res"

# logfiles




# scripts and binaries

plink="${home_directory}/bin/plink1.90"
gcta="${home_directory}/bin/gcta64"


matrixeqtl_run_r="${home_directory}/resources/genetics/matrixeqtl.R"





# bplink file name
# covariates filename
# phenotypes filename
# family or unrelated

# kinship file
# kinship file - relateds only

# genetic principal components
# smoking prediction
# age prediction

# cell count reference
# cell counts


