#!/usr/bin/env bash

# ID lists
intersect_ids_plink="${home_directory}/processed_data/ids/intersect_ids_plink.txt"
intersect_ids="${home_directory}/processed_data/ids/intersect_ids.txt"

# Clean genetic data
bfile="${home_directory}/processed_data/genetic_data/data"
tabfile="${home_directory}/processed_data/genetic_data/tabfile/data"
allele_ref="${home_directory}/processed_data/genetic_data/data.allele_codes"
bfile_hm3="${home_directory}/processed_data/genetic_data/data_hm3"
tabfile_hm3="${home_directory}/processed_data/genetic_data/tabfile_hm3/data"
allele_ref_hm3="${home_directory}/processed_data/genetic_data/data_hm3.allele_codes"

# cnv file
tabcnv="${home_directory}/processed_data/cnv_data/tabfile/data"

# Kinship files
grmfile_all="${home_directory}/processed_data/genetic_data/data"
grmfile_relateds="${home_directory}/processed_data/genetic_data/data_relateds"
grmfile_unrelateds="${home_directory}/processed_data/genetic_data/data_unrelateds"

# PCA files
pcs_all="${grmfile_all}.eigenvec"

# Cell count
cellcounts="${home_directory}/processed_data/methylation_data/cellcounts.txt"
cellcount_reference="${home_directory}/resources/cellcounts/houseman-dmrs.txt"

# Covariates
covariates_combined="${home_directory}/processed_data/methylation_data/all_covariates.txt"
meth_pcs="${home_directory}/processed_data/methylation_data/meth_pcs"
nongenetic_meth_pcs="${home_directory}/processed_data/methylation_data/meth_pcs_nongenetic"

# SNP list files
hm3_snps="${home_directory}/resources/genetics/hapmap3_autosome.snplist.gz"
ilmn_probesnps="${home_directory}/resources/qc/probesnps.txt"

# Sample mixup checks
bfile_probesnps="${bfile}_probesnps"

# ID lists
genetic_outlier_ids="${home_directory}/processed_data/genetic_data/genetic_outliers.txt"
methylation_ids="${home_directory}/processed_data/genetic_data/methylation_ids.txt"

# Methylation files
methylation_rt="${home_directory}/processed_data/methylation_data/methylation_rt"
methylation_rt_cc="${home_directory}/processed_data/methylation_data/methylation_rt_cc"
methylation_rt_cc_poly="${home_directory}/processed_data/methylation_data/methylation_rt_cc_poly"
methylation_rt_cc_poly_sq="${home_directory}/processed_data/methylation_data/methylation_rt_cc_poly_sq"

# Smoking prediction
smoking_pred="${home_directory}/processed_data/methylation_data/smoking_prediction.txt"

# Age prediction
age_pred="${home_directory}/processed_data/methylation_data/age_prediction.txt"

# Results locations
ewas_bmi_dir="${home_directory}/results/ewas_bmi"
ewas_height_dir="${home_directory}/results/ewas_height"
gwas_aar_dir="${home_directory}/results/gwas_aar"
gwas_cellcounts_dir="${home_directory}/results/gwas_cellcounts"
gwas_smoking_dir="${home_directory}/results/gwas_smoking"
matrixeqtl_mcnv_dir="${home_directory}/results/matrixeqtl_mcnv"
matrixeqtl_mqtl_dir="${home_directory}/results/matrixeqtl_mqtl"
matrixeqtl_vmqtl_dir="${home_directory}/results/matrixeqtl_vmqtl"
resname="res"

# logfiles



# scripts and binaries
plink="${home_directory}/bin/plink1.90"
gcta="${home_directory}/bin/gcta64"
