#!/usr/bin/env bash

# logfiles

section_01_dir="${home_directory}/results/01"
section_02_dir="${home_directory}/results/02"
section_03_dir="${home_directory}/results/03"
section_04_dir="${home_directory}/results/04"
section_05_dir="${home_directory}/results/05"
section_06_dir="${home_directory}/results/06"
section_07_dir="${home_directory}/results/07"
section_08_dir="${home_directory}/results/08"
section_09_dir="${home_directory}/results/09"
section_10_dir="${home_directory}/results/10"
section_11_dir="${home_directory}/results/11"
section_12_dir="${home_directory}/results/12"
section_13_dir="${home_directory}/results/13"
section_14_dir="${home_directory}/results/14"
section_15_dir="${home_directory}/results/15"

section_01_logfile="${section_01_dir}/logs/log.txt"
section_02a_logfile="${section_02_dir}/logs_a/log.txt"
section_02b_logfile="${section_02_dir}/logs_b/log.txt"
section_03a_logfile="${section_03_dir}/logs_a/log.txt"
section_03b_logfile="${section_03_dir}/logs_b/log.txt"
section_04a_logfile="${section_04_dir}/logs_a/log.txt"
section_04b_logfile="${section_04_dir}/logs_b/log.txt"
section_04c_logfile="${section_04_dir}/logs_c/log.txt"
section_04d_logfile="${section_04_dir}/logs_d/log.txt"
section_04e_logfile="${section_04_dir}/logs_e/log.txt"
section_04f_logfile="${section_04_dir}/logs_f/log.txt"
section_05_logfile="${section_05_dir}/logs/log.txt"
section_06_logfile="${section_06_dir}/logs/log.txt"
section_07_logfile="${section_07_dir}/logs/log.txt"
section_08a_logfile="${section_08_dir}/logs_a/log.txt"
section_08b_logfile="${section_08_dir}/logs_b/log.txt"
section_09_logfile="${section_09_dir}/logs/log.txt"
section_10_logfile="${section_10_dir}/logs/log.txt"
section_11_logfile="${section_11_dir}/logs/log.txt"
section_12_logfile="${section_12_dir}/logs/log.txt"
section_13_logfile="${section_13_dir}/logs/log.txt"
section_14_logfile="${section_14_dir}/logs/log.txt"
section_15_logfile="${section_15_dir}/logs/log.txt"

# ID lists
meth_ids="${home_directory}/processed_data/ids/meth_ids.txt"
intersect_ids_plink="${home_directory}/processed_data/ids/intersect_ids_plink.txt"
intersect_ids="${home_directory}/processed_data/ids/intersect_ids.txt"

# Check data
control_snps="${home_directory}/resources/genetics/snpsforbuildandposcheck.txt"
snpchrtxt="${section_01_dir}/no_snps_by_chr.txt"
snpchrplot="${section_01_dir}/no_snps_by_chr.pdf"
quality_scores_plot="${section_01_dir}/snp_quality.pdf"
ageplot="${section_01_dir}/age_distribution.pdf"
positive_control_cpg="cg07959070"
positive_control_snp_chr="22"
positive_control_snp_pos="50053871"
positive_control_snp_window="100000"
positive_control_threshold="0.001"


# Descriptives
genetic_descriptives="${home_directory}/processed_data/ids/genetic_descriptives.RData"
methylation_descriptives="${home_directory}/processed_data/ids/methylation_descriptives.RData"
cnv_descriptives="${home_directory}/processed_data/ids/cnv_descriptives.RData"
covariate_descriptives="${home_directory}/processed_data/ids/covariate_descriptives.RData"
phenotype_descriptives="${home_directory}/processed_data/ids/phenotype_descriptives.RData"
cohort_descriptives="${section_01_dir}/cohort_descriptives.RData"
methylation_summary="${section_01_dir}/methylation_summary.RData"

# EWAS phenotypes
ewasplot="${section_03_dir}/ewas_phenotypes.pdf"
ewastransformed="${home_directory}/processed_data/phenotypes/ewas.transformed.txt"
ewas_sd="5"
ewas_plink="${home_directory}/processed_data/phenotypes/ewas.plink"
ewas_file="${home_directory}/processed_data/phenotypes/ewas"
phenotype_list="${section_01_dir}/phenotype_list.txt"

# Clean genetic data
bfile="${home_directory}/processed_data/genetic_data/data"
tabfile="${home_directory}/processed_data/genetic_data/tabfile/data"
bfile_hm3="${home_directory}/processed_data/genetic_data/data_hm3"
tabfile_hm3="${home_directory}/processed_data/genetic_data/tabfile_hm3/data"
allele_ref_hm3="${home_directory}/processed_data/genetic_data/data_hm3.allele_codes"

pcaplot="${section_02_dir}/pcaplot.pdf"
allele_ref="${section_02_dir}/data.allele_codes.gz"
SNPfail1="${home_directory}/processed_data/genetic_data/SNPfail1.txt"
easyQC="${home_directory}/processed_data/genetic_data/data.easyqc"
easyQCfile="${home_directory}/processed_data/genetic_data/CLEANED.data.easyqc.gz"
easyQCscript="${home_directory}/resources/genetics/easyQC.ecf"


# CNV file
tabcnv="${home_directory}/processed_data/cnv_data/tabfile/data"

# Kinship files
grmfile_all="${home_directory}/processed_data/genetic_data/data"
grmfile_relateds="${home_directory}/processed_data/genetic_data/data_relateds"
grmfile_unrelateds="${home_directory}/processed_data/genetic_data/data_unrelateds"

# PCA files
pca="${home_directory}/processed_data/genetic_data/pca"
pcs_all="${pca}.eigenvec"

# Cell count
cellcounts="${home_directory}/processed_data/methylation_data/cellcounts.txt"
cellcounts_reference="blood_gse35069_complete"
cellcounts_tf="${home_directory}/processed_data/cellcounts/cellcounts.transformed.txt"
cellcounts_tf_smok="${home_directory}/processed_data/cellcounts/cellcounts.transformed.smokingadj.txt"
cellcounts_entropy="${home_directory}/processed_data/cellcounts/cellcounts_entropy.txt"
cellcounts_plink="${home_directory}/processed_data/cellcounts/cellcounts.transformed.plink"
cellcounts_plink_raw="${home_directory}/processed_data/cellcounts/cellcounts.raw.plink"
cellcounts_plink_smokadj="${home_directory}/processed_data/cellcounts/cellcounts.transformed.smokadj.plink"
cellcounts_SD="5"
cellcounts_plot="${section_04_dir}/cellcounts_plot.pdf"
cellcounts_gwa="${home_directory}/processed_data/cellcounts/cellcounts.houseman.txt"
cellcounts_cov="${home_directory}/processed_data/cellcounts/cellcounts.covariates.txt"

# Covariates
covariates_combined="${home_directory}/processed_data/methylation_data/all_covariates"
meth_pcs="${home_directory}/processed_data/methylation_data/meth_pcs"
nongenetic_meth_pcs="${home_directory}/processed_data/methylation_data/meth_pcs_nongenetic"
gwas_covariates="${home_directory}/processed_data/genetic_data/gwas_covariates"

# SNP list files
hm3_snps="${home_directory}/resources/genetics/hapmap3_autosome.snplist.gz"
ilmn_probesnps="${home_directory}/resources/qc/probesnps.txt"
hm3_snps_no_ld="${home_directory}/resources/genetics/hapmap3_autosome.snplist_withoutlong-range.LDSNPs.txt.gz"

# Sample mixup checks
bfile_probesnps="${bfile}_probesnps"

# ID lists
genetic_outlier_ids="${home_directory}/processed_data/genetic_data/genetic_outliers.txt"
methylation_ids="${home_directory}/processed_data/genetic_data/methylation_ids.txt"

# Methylation files
methylation_adjusted="${home_directory}/processed_data/methylation_data/methylation_adjusted"
methylation_adjusted_pcs="${home_directory}/processed_data/methylation_data/methylation_adjusted_pcs"
methylation_adjusted_pcs_sq="${home_directory}/processed_data/methylation_data/methylation_adjusted_pcs_sq"

# Smoking prediction
methylation_processed_dir="${home_directory}/processed_data/methylation_data"
smoking_pred="${methylation_processed_dir}/smoking_prediction"
smoking_pred_plot="${section_04_dir}/smoking_prediction.pdf"
smoking_pred_SD="5"


# Age prediction
age_pred="${home_directory}/processed_data/methylation_data/age_prediction"
age_pred_plot="${section_04_dir}/age_prediction.pdf"
age_pred_SD="5"

# Results locations
matrixeqtl_mqtl_dir="${home_directory}/results/05"
matrixeqtl_vmqtl_dir="${home_directory}/results/06"
matrixeqtl_mcnv_dir="${home_directory}/results/07"
ewas_results_dir="${home_directory}/results/08"
gwas_aar_dir="${home_directory}/results/09"
gwas_smoking_dir="${home_directory}/results/10"
gwas_cellcount_entropy_dir="${home_directory}/results/11"
gwas_cellcounts_dir="${home_directory}/results/12"
gwas_cellcounts_mvlmm_dir="${home_directory}/results/13"

resname="res"

#height prediction
height_snps_wood="${home_directory}/resources/genetics/wood.height.snps_af0.1"
height_snps="${home_directory}/processed_data/genetic_data/height"
height_plot="${section_03_dir}/heightcor_plot.pdf"


# SFTP details
# This is the location your results will be uploaded
# Note: No individual data will be uploaded to this location during the course of the pipeline
sftp_address="sscmv-filetran.epi.bris.ac.uk"

if [ "$sftp_username" = "gh13047" ] || [ "$sftp_username" = "epzjlm" ] || [ "$sftp_username" = "godmc" ]
then
	sftp_path="/srv/sftponly/GoDMC"
else
	sftp_path="/GoDMC"
fi

# scripts and binaries
plink="${home_directory}/resources/bin/plink1.90"
gcta="${home_directory}/resources/bin/gcta64"
gemma="${home_directory}/resources/bin/gemma"




# Functions

print_version () {

	version=`git tag | tail -n 1`
	commit=`git rev-parse HEAD`
	commit_date=`git show -s --format=%ci`
	current_time=`date`
	echo ""
	echo ""
	echo "GoDMC version ${version}"
	echo "Commit: ${commit}"	
	echo "Commit date: ${commit_date}"
	echo "Current time: ${current_time}"
	echo ""
	echo "Please ensure your scripts are up to date."
	echo "If in doubt, run 'git pull'"
	echo ""
	echo ""

}

